<!DOCTYPE html>
<html lang="en">
  <head>



    <meta charset="utf-8">
    <title>Member Data Update Panel</title>

<!--
put the PDQ Flyers logo first
-->

<img src="http://www.pdqflyers.com/PDQ-banner.jpg"/>

<!--
We need to be able to hide the maac and last name parameters that we need to pass to data-write.php but don't want the viewer to see

The button code in the Style section was generated by a web page tool called "Button Builder", a free tool found at: http://livetools.uiparade.com/button-builder.html#
You set up the button that you want and it generates the CSS code that you then embed in your Head Section.
-->
<style type="text/css">

.hide {display:none;}
.red {color:red}
button {
   border: 1px solid #0a3c59;
   background: #4d7c8a;
   background: -webkit-gradient(linear, left top, left bottom, from(#a2e8aa), to(#4d7c8a));
   background: -webkit-linear-gradient(top, #a2e8aa, #4d7c8a);
   background: -moz-linear-gradient(top, #a2e8aa, #4d7c8a);
   background: -ms-linear-gradient(top, #a2e8aa, #4d7c8a);
   background: -o-linear-gradient(top, #a2e8aa, #4d7c8a);
   background-image: -ms-linear-gradient(top, #a2e8aa 0%, #4d7c8a 100%);
   padding: 10.5px 21px;
   -webkit-border-radius: 6px;
   -moz-border-radius: 6px;
   border-radius: 6px;
   -webkit-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   -moz-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   text-shadow: #7ea4bd 0 1px 0;
   color: #010305;
   font-size: 14px;
   font-family: helvetica, serif;
   text-decoration: none;
   vertical-align: middle;
   }
button:hover {
   border: 1px solid #0a3c59;
   text-shadow: #1e4158 0 1px 0;
   background: #3e779d;
   background: -webkit-gradient(linear, left top, left bottom, from(#46a887), to(#3e779d));
   background: -webkit-linear-gradient(top, #46a887, #3e779d);
   background: -moz-linear-gradient(top, #46a887, #3e779d);
   background: -ms-linear-gradient(top, #46a887, #3e779d);
   background: -o-linear-gradient(top, #46a887, #3e779d);
   background-image: -ms-linear-gradient(top, #46a887 0%, #3e779d 100%);
   color: #fff;
   }
button:active {
   text-shadow: #1e4158 0 1px 0;
   border: 1px solid #0a3c59;
   background: #65a9d7;
   background: -webkit-gradient(linear, left top, left bottom, from(#3e779d), to(#3e779d));
   background: -webkit-linear-gradient(top, #3e779d, #65a9d7);
   background: -moz-linear-gradient(top, #3e779d, #65a9d7);
   background: -ms-linear-gradient(top, #3e779d, #65a9d7);
   background: -o-linear-gradient(top, #3e779d, #65a9d7);
   background-image: -ms-linear-gradient(top, #3e779d 0%, #65a9d7 100%);
   color: #fff;
   }

</style>
    

  </head>
  <body>



<p><span style="FONT-SIZE: 24pt"><strong><font color="#0000ff">Member Data Update Details</font></strong></span></p>

<h3>Member Data</h3>

<!--
This page is invoked from the Membership page in the PDQ Flyers website. Its purpose is to allow the Member to change or add data fields to their membership data record on our website.  
Updating, or at least confirming, contact and preference data is also the first step in the new or renewal application process as well.
-->

<div class="entries">

<?php
// get the identification data that was passed to this program in the hidden form
$maac = $_REQUEST['request_maac'];
$lname = $_REQUEST['request_lname'];


/* 
set up key words so that if data base names or passwords change later, you only have to change them here 
and connect to the server and open the data base
*/

$username="pdqf2438_PDQmbr";$password="chipmunk2";$database="pdqf2438_members"; 
mysql_connect(localhost,$username,$password); 


@mysql_select_db($database) or die( "Unable to open the database - contact the webmaster");


/*
set up the query using the MAAC number that was passed
Execute the query to get the member's record - the recordset $rs contains the result
check to make sure that the query retrieved a real record
if it didn't, send a message to the operator and let him go back to the application screen to enter the correct MAAC number
*/

$strSQL = "SELECT * FROM members WHERE maac = '$maac'";
$rs = mysql_query($strSQL);
if(! mysql_num_rows($rs)>0) {echo "The MAAC number you entered doesn't exist on our database.  "; 
die("Go back to the update request tab in your Browser and correct your input.");}

/* 
create a one line array and extract all of the member's data into variables for easy access later.
*/

while($row = mysql_fetch_array($rs)) 
{
$fname = $row['first_name'];
$last_name = $row['last_name'];
$email = $row['email'];
$address = $row['address'];
$city = $row['city'];
$postal = $row['postal_code'];
$hphone = $row['home_phone'];
$mphone = $row['mobile_phone'];
$member_since = $row['member_since'];
$instructor = $row['instructor'];
$myear = $row['membership_year'];
$mtype= $row['member_type'];
$p_name = $row['p_name'];
$p_address = $row['p_address'];
$p_phone = $row['p_phone'];
$p_photo = $row['p_photo'];
$g_general = $row['g_general'];
$g_scale = $row['g_scale'];
$g_heli = $row['g_heli'];
$g_indoor = $row['g_indoor'];
$g_float = $row['g_float'];
}

$last_name = strtolower($last_name);
$lname = strtolower($lname);

if ($lname <> $last_name) {echo "The MAAC number and last name combination you entered doesn't exist on our database.  "; 
die("Use the back arrow on your Browser to go back and correct your input.");}

?>
<p>Your MAAC number and last name have been used to access your personal information from the Club's database.  </p>

<p>You may write in or modify the text in any of the data entry boxes below.  Boxes marked wth an '*' are required information.<br>
If data items not listed here need to be changed, please contact the <a href = "mailto:webmaster@pdqflyers.com">Webmaster</a>.</p>

<p> When you are satisfied with the changes that you have made, click on the "Update my Data" button, and you will be transferred to a screen which will review your input, make the changes you requested,
 and provide a report on what was done.<br></p>
<p>If you are either a new or renewing member and have reached this page to submit your request for a Membership Card, 
you will have the opportunity to do that when your data is reviewed and, if necessary, updated.</p>

<!-- 
Set up the form with all the member fields present and populate them with the data that was extracted from the database
There are 3 fields that haven't been included: membership_year, application_data, and member_type are filled in when the application is done and aren't changeable.
Headshot is completed manually by the webmaster via phpMyAdmin.
-->

<form method="post" 
      action="data-write.php">

<fieldset id="keys" class ="hide"> 


<label>MAAC#: *</label> <br><input size="12"
                  name="updater_maac" value = "<?php echo htmlspecialchars($maac); ?>" /><br>
<label>Last Name: *</label> <br><input size="30"
                  name="updater_lname" value = "<?php echo htmlspecialchars($lname); ?>" /><br>
 </fieldset>

    <fieldset id="contact"> <legend><strong>Contact Information</strong></legend>

<label>First Name: *</label> <br><input size="30"
                  name="updater_fname" value = "<?php echo htmlspecialchars($fname); ?>" /><br>
<label>eMail: *</label> <br><input size="30"
                  name="updater_email" value = "<?php echo htmlspecialchars($email); ?>" /><br>
<label>Address: *</label> <br><input size="30"
                  name="updater_address" value = "<?php echo htmlspecialchars($address); ?>" /><br>
<label>City: *</label> <br><input size="30"
                  name="updater_city" value = "<?php echo htmlspecialchars($city); ?>" /><br>
<label>Postal Code: *</label> <br><input size="7"
                  name="updater_PC" value = "<?php echo htmlspecialchars($postal); ?>" /><br>
<label>Home Phone:</label> <br><input size="12"
                  name="updater_hphone" value = "<?php echo htmlspecialchars($hphone); ?>" /><br>
<label>Mobile Phone:</label> <br><input size="12"
                  name="updater_mphone" value = "<?php echo htmlspecialchars($mphone); ?>" /><br>
<label>Member Since (yyyy):</label> <br><input size="4"
                  name="updater_msince" value = "<?php echo htmlspecialchars($member_since); ?>" /><br>

<p><label>Instructor: </label> <input type="checkbox"
                  name="updater_instructor" <?php if ($instructor) {echo 'checked="checked"';} ?> /></p>
<!-- I put the span in here to make all the printing for the Treasuer's area red -->
<span class="red"><p><label>Treasurer Password:</label> <input size="8" type ="password"
                  name="updater_mpswd"/></p>
    
<label>&nbsp;&nbsp;Membership Year:  </label> <input size="4"
    name="updater_myear" value = "<?php echo htmlspecialchars($myear); ?>" />
    </p>

    <p>
Member Type: 
<select name="updater_mtype">
  <option value="<?php echo htmlspecialchars($mtype); ?>"><?php echo htmlspecialchars($mtype); ?></option>
  <option value="Full">Full</option>
  <option value="Junior">Junior</option>
  <option value="Social">Social</option>
  <option value="Associate">Associate</option>
</select>
</p>
</span>

    </fieldset>

<fieldset id="interests"> 
    <legend><strong>Special Interests</strong></legend>

<p>Checking any of these boxes will allow you to send and receive broadcast emails related to these groups.<br>

<label>General Interest:</label><input type = "checkbox"
                  name="updater_general" <?php if ($g_general) {echo 'checked="checked"';} ?>/>&nbsp;&nbsp;&nbsp;
<label>Indoor Flying:</label><input type = "checkbox"
                  name="updater_indoor" <?php if ($g_indoor) {echo 'checked="checked"';} ?>/>&nbsp;&nbsp;&nbsp;
<label>Float Flying:</label> <input type = "checkbox"
                  name="updater_float" <?php if ($g_float) {echo 'checked="checked"';} ?>/>&nbsp;&nbsp;&nbsp;
<label>Helicopters:</label> <input type = "checkbox"
                  name="updater_heli" <?php if ($g_heli) {echo 'checked="checked"';} ?>/>&nbsp;&nbsp;&nbsp;
<label>Scale:</label> <input type = "checkbox"
                  name="updater_scale" <?php if ($g_scale) {echo 'checked="checked"';} ?>/><br>
    </fieldset>

<fieldset id="privacy"> 
<legend><strong>Privacy Information</strong></legend>

<p>Checking the name box means that no Member Page will be created for you in the Member's Only Section.<br>
Checking any of the other boxes will stop that information from being published on our website.<br>

<label>Name:</label><input type = "checkbox"
                  name="updater_pname" <?php if ($p_name) {echo 'checked="checked"';} ?>/>&nbsp;&nbsp;&nbsp;
<label>Address:</label> <input type = "checkbox"
                  name="updater_paddress" <?php if ($p_address) {echo 'checked="checked"';} ?>/>&nbsp;&nbsp;&nbsp;
<label>Phone Numbers:</label> <input type = "checkbox"
                  name="updater_pphone" <?php if ($p_phone) {echo 'checked="checked"';} ?>/>&nbsp;&nbsp;&nbsp;
<label>Head Shot:</label> <input type = "checkbox"
                  name="updater_pphoto" <?php if ($p_photo) {echo 'checked="checked"';} ?>/><br>
    </fieldset>

    <button type="submit">
        <!--
<img src="procede.jpg" width="50" height="50" alt="Submit Request" />
        -->
 Update My Data</button>
</form>

<!php mysql_close();         // close the data base ?> 

</div>
</body>
</html>